service: getparrot

provider:
  name: aws
  runtime: python3.7

  region: us-east-1

  timeout: 20

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource:
        - "*"

functions:
  getparrot:
    handler: getparrot.getparrot
    events:
      - schedule: rate(1 day)
